# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install .NET Aspire workload
      run: dotnet workload install aspire

    - name: Update workload
      run: dotnet workload update
      
    - name: Restore dependencies
      run: cd AppHouse && dotnet restore
    - name: Build
      run: cd AppHouse && dotnet build --no-restore
    - name: Test
      run: cd AppHouse && dotnet test --no-build --verbosity normal
